export const RETRIEVE_COUNTRIES = 'RETRIEVE_COUNTRIES';
export const RETRIEVE_PRICES = 'RETRIEVE_PRICES';
export const CREATE_PARCEL = 'CREATE_PARCEL';
export const RETRIEVE_PARCELS = 'RETRIEVE_PARCELS';
export const DELETE_PARCEL = 'DELETE_PARCEL';
export const UPDATE_PARCEL = 'UPDATE_PARCEL';
